export interface EmojiCategory {
  id: string;
  title: string;
  icon: string;
  keywords?: string[];
  items: string[];
}

export const EMOJI_RECENTS_ID = "recent";
const EMOJI_FALLBACK_RECENTS = ["👍", "❤️", "😂", "😊", "🔥", "😍", "🙏", "👏", "🥰", "😁", "✨", "🎉"];

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "smileys",
    title: "Смайлы",
    icon: "😀",
    keywords: ["smile", "face", "emotion", "улыб", "смех", "радост", "грусть", "зл"],
    items: [
      "😀",
      "😃",
      "😄",
      "😁",
      "😆",
      "😅",
      "😂",
      "🤣",
      "🥲",
      "😊",
      "😇",
      "🙂",
      "🙃",
      "😉",
      "😌",
      "😍",
      "🥰",
      "😘",
      "😗",
      "😙",
      "😚",
      "😋",
      "😛",
      "😜",
      "🤪",
      "😝",
      "🤑",
      "🤗",
      "🤭",
      "🤫",
      "🤔",
      "🤐",
      "🤨",
      "😐",
      "😑",
      "😶",
      "😏",
      "😒",
      "🙄",
      "😬",
      "🤥",
      "😔",
      "😪",
      "🤤",
      "😴",
      "😷",
      "🤒",
      "🤕",
      "🤢",
      "🤮",
      "🤧",
      "😵",
      "🤯",
      "🤠",
      "🥳",
      "😎",
      "🤓",
      "🧐",
      "😕",
      "😟",
      "🙁",
      "☹️",
      "😮",
      "😯",
      "😲",
      "😳",
      "🥺",
      "😢",
      "😭",
      "😤",
      "😠",
      "😡",
      "🤬",
      "😱",
      "😨",
      "😰",
      "😥",
      "😓",
      "😞",
      "😖",
      "😣",
      "😩",
      "😫",
      "😵‍💫",
      "😮‍💨",
      "🥴",
    ],
  },
  {
    id: "people",
    title: "Люди и жесты",
    icon: "🧑",
    keywords: ["people", "hand", "gesture", "человек", "рука", "жест", "лайк"],
    items: [
      "👋",
      "🤚",
      "🖐️",
      "✋",
      "🖖",
      "👌",
      "🤌",
      "🤏",
      "✌️",
      "🤞",
      "🤟",
      "🤘",
      "🤙",
      "👈",
      "👉",
      "👆",
      "🖕",
      "👇",
      "👍",
      "👎",
      "✊",
      "👊",
      "🤛",
      "🤜",
      "🤝",
      "🙌",
      "👏",
      "🫶",
      "🙏",
      "💪",
      "🦾",
      "🧠",
      "👀",
      "👁️",
      "👂",
      "👃",
      "🫡",
      "🙋‍♀️",
      "🙋‍♂️",
      "🙆‍♀️",
      "🙆‍♂️",
      "🙅‍♀️",
      "🙅‍♂️",
      "🤷‍♀️",
      "🤷‍♂️",
      "💁‍♀️",
      "💁‍♂️",
      "🙇‍♀️",
      "🙇‍♂️",
    ],
  },
  {
    id: "nature",
    title: "Животные и природа",
    icon: "🐻",
    keywords: ["animal", "nature", "pet", "живот", "природ", "цвет"],
    items: [
      "🐶",
      "🐱",
      "🐭",
      "🐹",
      "🐰",
      "🦊",
      "🐻",
      "🐼",
      "🐨",
      "🐯",
      "🦁",
      "🐮",
      "🐷",
      "🐽",
      "🐸",
      "🐵",
      "🐔",
      "🐧",
      "🐦",
      "🐤",
      "🐣",
      "🐥",
      "🐺",
      "🦄",
      "🐝",
      "🐛",
      "🦋",
      "🐌",
      "🐞",
      "🐜",
      "🐢",
      "🐍",
      "🐙",
      "🦑",
      "🦀",
      "🐠",
      "🐟",
      "🐡",
      "🐬",
      "🐳",
      "🐋",
      "🐊",
      "🦈",
      "🐆",
      "🐅",
      "🐘",
      "🦌",
      "🐪",
      "🐫",
      "🦒",
      "🦓",
      "🐇",
      "🐿️",
      "🦔",
      "🌸",
      "🌼",
      "🌻",
      "🌺",
      "🌹",
      "🌷",
      "🌱",
      "🌲",
      "🌳",
      "🍀",
      "🍁",
      "🍂",
      "🍃",
    ],
  },
  {
    id: "food",
    title: "Еда и напитки",
    icon: "🍔",
    keywords: ["food", "drink", "еда", "напит", "вкус"],
    items: [
      "🍎",
      "🍐",
      "🍊",
      "🍋",
      "🍌",
      "🍉",
      "🍇",
      "🍓",
      "🍒",
      "🍑",
      "🍍",
      "🥭",
      "🥝",
      "🍅",
      "🍆",
      "🥑",
      "🥦",
      "🥕",
      "🌽",
      "🌶️",
      "🥒",
      "🥬",
      "🍄",
      "🥜",
      "🌰",
      "🍞",
      "🥐",
      "🥖",
      "🥨",
      "🥯",
      "🧀",
      "🍖",
      "🍗",
      "🥩",
      "🥓",
      "🍔",
      "🍟",
      "🍕",
      "🌭",
      "🥪",
      "🌮",
      "🌯",
      "🥙",
      "🧆",
      "🥚",
      "🍳",
      "🥘",
      "🍲",
      "🥣",
      "🥗",
      "🍿",
      "🧈",
      "🧂",
      "🍱",
      "🍣",
      "🍤",
      "🍙",
      "🍚",
      "🍛",
      "🍜",
      "🍝",
      "🍠",
      "🍢",
      "🍡",
      "🍧",
      "🍨",
      "🍦",
      "🧁",
      "🍰",
      "🎂",
      "🍪",
      "🍩",
      "🍫",
      "🍬",
      "🍭",
      "🍮",
      "🍯",
      "☕️",
      "🍵",
      "🥤",
      "🧃",
      "🥛",
      "🍺",
      "🍻",
      "🍷",
      "🥂",
      "🥃",
      "🍸",
      "🍹",
      "🍾",
    ],
  },
  {
    id: "activity",
    title: "Активность",
    icon: "⚽️",
    keywords: ["sport", "game", "music", "спорт", "игр", "музык"],
    items: [
      "⚽️",
      "🏀",
      "🏈",
      "⚾️",
      "🥎",
      "🎾",
      "🏐",
      "🏉",
      "🎱",
      "🏓",
      "🏸",
      "🏒",
      "🥍",
      "🥏",
      "⛳️",
      "🏹",
      "🎣",
      "🥊",
      "🥋",
      "🎽",
      "🛹",
      "🛼",
      "🚴‍♀️",
      "🚴‍♂️",
      "🧗‍♀️",
      "🧗‍♂️",
      "🏊‍♀️",
      "🏊‍♂️",
      "🤽‍♀️",
      "🤽‍♂️",
      "🚣‍♀️",
      "🚣‍♂️",
      "🏄‍♀️",
      "🏄‍♂️",
      "🏇",
      "🧘‍♀️",
      "🧘‍♂️",
      "🎮",
      "🎲",
      "🎯",
      "🎳",
      "🎹",
      "🎸",
      "🎺",
      "🎷",
      "🥁",
      "🎤",
      "🎧",
      "🎨",
      "🎭",
      "🎪",
      "🎟️",
      "🎫",
      "🏆",
      "🥇",
      "🥈",
      "🥉",
      "🎉",
      "🎊",
      "🎆",
      "🎇",
    ],
  },
  {
    id: "travel",
    title: "Путешествия",
    icon: "✈️",
    keywords: ["travel", "transport", "город", "машин", "путеш"],
    items: [
      "🚗",
      "🚕",
      "🚙",
      "🚌",
      "🚎",
      "🚓",
      "🚑",
      "🚒",
      "🚚",
      "🚛",
      "🚲",
      "🛴",
      "🛵",
      "🏍️",
      "🚜",
      "🚂",
      "🚃",
      "🚄",
      "🚅",
      "🚆",
      "🚇",
      "🚊",
      "🚉",
      "✈️",
      "🛫",
      "🛬",
      "🛩️",
      "🚀",
      "🛸",
      "🚁",
      "🚤",
      "⛵️",
      "🛶",
      "🚢",
      "🗺️",
      "🗿",
      "🗽",
      "🗼",
      "🏰",
      "🏯",
      "🏟️",
      "🎡",
      "🎢",
      "🎠",
      "🏖️",
      "🏝️",
      "🏜️",
      "🏕️",
      "🗻",
      "🌋",
      "🏙️",
      "🌁",
      "🏘️",
      "🏠",
      "🏡",
      "🏢",
      "🏬",
      "🏭",
      "🏫",
      "🏥",
      "🏦",
    ],
  },
  {
    id: "objects",
    title: "Объекты",
    icon: "💡",
    keywords: ["object", "tech", "предмет", "вещ"],
    items: [
      "⌚️",
      "📱",
      "💻",
      "🖥️",
      "🖨️",
      "🖱️",
      "🖲️",
      "🕹️",
      "💾",
      "💿",
      "📀",
      "📷",
      "📸",
      "🎥",
      "📹",
      "📺",
      "📻",
      "🎙️",
      "🎚️",
      "🎛️",
      "⌨️",
      "🧮",
      "📡",
      "🔋",
      "🔌",
      "💡",
      "🔦",
      "🕯️",
      "🧹",
      "🧺",
      "🧻",
      "🚪",
      "🪑",
      "🛋️",
      "🛏️",
      "🛁",
      "🚿",
      "🧼",
      "🧴",
      "🪒",
      "🗝️",
      "🔑",
      "🧸",
      "🎁",
      "🎈",
      "🎉",
      "🧨",
      "📎",
      "📌",
      "🧷",
      "📏",
      "📐",
      "✂️",
      "🧪",
      "🧫",
      "🧬",
      "🔬",
      "🔭",
      "📦",
      "📫",
      "📮",
      "📖",
      "📚",
      "🗂️",
      "📋",
      "📝",
      "✏️",
      "🖊️",
      "🖍️",
      "🗓️",
      "🔒",
      "🔓",
      "🔔",
      "🔕",
    ],
  },
  {
    id: "symbols",
    title: "Символы",
    icon: "❤️",
    keywords: ["symbol", "heart", "star", "символ", "сердц", "зв"],
    items: [
      "❤️",
      "🧡",
      "💛",
      "💚",
      "💙",
      "💜",
      "🖤",
      "🤍",
      "🤎",
      "💔",
      "❣️",
      "💕",
      "💞",
      "💓",
      "💗",
      "💖",
      "💘",
      "💝",
      "💟",
      "☮️",
      "✝️",
      "☪️",
      "☸️",
      "✡️",
      "🔯",
      "🕉️",
      "☯️",
      "☦️",
      "☘️",
      "✳️",
      "❇️",
      "✅",
      "☑️",
      "✔️",
      "✖️",
      "❌",
      "➕",
      "➖",
      "➗",
      "❗️",
      "❓",
      "❕",
      "❔",
      "⚠️",
      "🚫",
      "⛔️",
      "🛑",
      "♻️",
      "🔰",
      "🎵",
      "🎶",
      "🌐",
      "🔴",
      "🟠",
      "🟡",
      "🟢",
      "🔵",
      "🟣",
      "⚫️",
      "⚪️",
      "🟤",
      "⭐️",
      "🌟",
      "✨",
      "💫",
      "🔥",
      "💥",
      "☀️",
      "🌙",
      "🌈",
      "💯",
    ],
  },
  {
    id: "flags",
    title: "Флаги",
    icon: "🏳️",
    keywords: ["flag", "country", "флаг", "страна"],
    items: [
      "🇷🇺",
      "🇺🇸",
      "🇬🇧",
      "🇫🇷",
      "🇩🇪",
      "🇮🇹",
      "🇪🇸",
      "🇺🇦",
      "🇨🇳",
      "🇯🇵",
      "🇰🇷",
      "🇮🇳",
      "🇧🇷",
      "🇨🇦",
      "🇦🇺",
      "🇲🇽",
      "🇹🇷",
      "🇸🇦",
      "🇸🇪",
      "🇳🇴",
      "🇫🇮",
      "🇳🇱",
      "🇵🇱",
      "🇨🇿",
      "🇬🇷",
      "🇮🇱",
      "🇦🇪",
      "🇦🇷",
      "🇨🇱",
      "🇵🇹",
      "🇨🇴",
    ],
  },
];

const EMOJI_KEYWORDS: Record<string, string[]> = {
  "😀": ["smile", "grin", "улыб"],
  "😂": ["lol", "laugh", "смех"],
  "🤣": ["lol", "laugh", "смех"],
  "😍": ["love", "heart", "любов", "влюб"],
  "🥰": ["love", "heart", "любов"],
  "😭": ["cry", "sad", "слез", "плак"],
  "😢": ["cry", "sad", "слез"],
  "😡": ["angry", "зл", "гнев"],
  "🤬": ["angry", "зл"],
  "👍": ["thumb", "like", "лайк", "ок"],
  "👎": ["thumb", "dislike", "диз", "не"],
  "🙏": ["pray", "please", "спасиб", "мол"],
  "🔥": ["fire", "hot", "огонь"],
  "💯": ["100", "сто"],
  "🎉": ["party", "празд", "celebrate"],
  "❤️": ["heart", "love", "сердц"],
  "💔": ["heart", "broken", "разбит"],
  "⚽️": ["sport", "soccer", "футбол"],
  "🏠": ["home", "дом"],
  "☀️": ["sun", "солнец", "день"],
  "🌙": ["moon", "луна", "ноч"],
};

export const DEFAULT_EMOJI: string[] = EMOJI_CATEGORIES.flatMap((c) => c.items);

function normalizeQuery(raw: string): string {
  return String(raw || "").trim().toLowerCase();
}

function matchesKeyword(query: string, keywords?: string[]): boolean {
  if (!keywords || !keywords.length) return false;
  const parts = query.split(/\s+/g).filter(Boolean);
  if (!parts.length) return false;
  for (const part of parts) {
    for (const kw of keywords) {
      if (kw.includes(part)) return true;
    }
  }
  return false;
}

function matchesEmoji(emoji: string, query: string, categoryKeywords?: string[]): boolean {
  if (!query) return true;
  if (emoji.includes(query)) return true;
  if (matchesKeyword(query, EMOJI_KEYWORDS[emoji])) return true;
  return matchesKeyword(query, categoryKeywords);
}

export function buildEmojiSections(recents: string[]): EmojiCategory[] {
  const safeRecents = Array.isArray(recents) ? recents.filter((x) => typeof x === "string" && x) : [];
  const recentItems = safeRecents.length ? safeRecents : EMOJI_FALLBACK_RECENTS;
  const recentSection: EmojiCategory = {
    id: EMOJI_RECENTS_ID,
    title: "Недавние",
    icon: "🕒",
    keywords: ["recent", "history", "недавн", "част"],
    items: recentItems,
  };
  return [recentSection, ...EMOJI_CATEGORIES];
}

export function filterEmojiSections(sections: EmojiCategory[], query: string): EmojiCategory[] {
  const q = normalizeQuery(query);
  if (!q) return sections;
  const out: EmojiCategory[] = [];
  for (const section of sections) {
    const categoryHit = matchesKeyword(q, section.keywords);
    const items = categoryHit
      ? section.items
      : section.items.filter((emoji) => matchesEmoji(emoji, q, section.keywords));
    if (!items.length) continue;
    out.push({ ...section, items });
  }
  return out;
}

export function insertTextAtSelection(opts: {
  value: string;
  selectionStart?: number | null;
  selectionEnd?: number | null;
  insertText: string;
}): { value: string; caret: number } {
  const value = String(opts.value ?? "");
  const insertText = String(opts.insertText ?? "");
  const maxPos = value.length;
  const startRaw = typeof opts.selectionStart === "number" ? opts.selectionStart : maxPos;
  const endRaw = typeof opts.selectionEnd === "number" ? opts.selectionEnd : startRaw;

  const start = Math.max(0, Math.min(maxPos, startRaw));
  const end = Math.max(0, Math.min(maxPos, endRaw));
  const a = Math.min(start, end);
  const b = Math.max(start, end);

  const next = value.slice(0, a) + insertText + value.slice(b);
  return { value: next, caret: a + insertText.length };
}

export function updateEmojiRecents(prev: string[], emoji: string, max: number): string[] {
  const e = String(emoji || "").trim();
  if (!e) return Array.isArray(prev) ? prev : [];
  const safePrev = Array.isArray(prev) ? prev.filter((x) => typeof x === "string" && x) : [];
  const dedup = safePrev.filter((x) => x !== e);
  const next = [e, ...dedup];
  return next.slice(0, Math.max(1, Math.min(200, max || 0)));
}

export function mergeEmojiPalette(recents: string[], base: string[]): string[] {
  const r = Array.isArray(recents) ? recents.filter((x) => typeof x === "string" && x) : [];
  const b = Array.isArray(base) ? base.filter((x) => typeof x === "string" && x) : [];
  const seen = new Set<string>();
  const out: string[] = [];
  for (const x of [...r, ...b]) {
    if (seen.has(x)) continue;
    seen.add(x);
    out.push(x);
  }
  return out;
}
